class InsertBlastManager {
  normalizeConfig(config = {}) {
    const tablePrefix = String(config.tablePrefix || 'IBLAST').trim().toUpperCase().replace(/[^A-Z0-9_$#]/g, '');
    const tableCount = Math.max(1, Math.min(5000, Number.parseInt(config.tableCount, 10) || 8));
    const columnsPerTable = Math.max(4, Math.min(200, Number.parseInt(config.columnsPerTable, 10) || 24));

    if (!tablePrefix) {
      throw new Error('Table prefix is required.');
    }

    return {
      tablePrefix,
      tableCount,
      columnsPerTable
    };
  }

  getTableNames(config = {}) {
    const normalized = this.normalizeConfig(config);
    return Array.from({ length: normalized.tableCount }, (_, index) => (
      `${normalized.tablePrefix}_T${String(index + 1).padStart(3, '0')}`
    ));
  }

  buildColumnDefinitions(columnsPerTable) {
    const columns = [
      'id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
      'created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL'
    ];

    for (let index = 1; index <= columnsPerTable; index += 1) {
      const suffix = String(index).padStart(3, '0');
      if (index % 3 === 1) {
        columns.push(`vc_${suffix} VARCHAR2(100)`);
      } else if (index % 3 === 2) {
        columns.push(`num_${suffix} NUMBER(18,2)`);
      } else {
        columns.push(`dt_${suffix} DATE`);
      }
    }

    return columns;
  }

  generateCreateTableDDL(tableName, columnsPerTable) {
    const columns = this.buildColumnDefinitions(columnsPerTable);
    return `CREATE TABLE ${tableName} (\n  ${columns.join(',\n  ')}\n) NOLOGGING`;
  }

  async createTables(oracleDb, config = {}, progressCallback = () => {}) {
    const normalized = this.normalizeConfig(config);
    const tableNames = this.getTableNames(normalized);
    const connection = await oracleDb.getConnection();

    try {
      for (let index = 0; index < tableNames.length; index += 1) {
        const tableName = tableNames[index];
        progressCallback({
          step: `Creating ${tableName}...`,
          progress: Math.round((index / tableNames.length) * 100)
        });
        await connection.execute(this.generateCreateTableDDL(tableName, normalized.columnsPerTable), [], {
          autoCommit: false
        });
      }

      await connection.commit();
      progressCallback({
        step: `Created ${tableNames.length} insert-blast table(s).`,
        progress: 100
      });

      return {
        config: normalized,
        tableNames
      };
    } finally {
      await connection.close();
    }
  }

  async dropTables(oracleDb, config = {}, progressCallback = () => {}) {
    const normalized = this.normalizeConfig(config);
    const tableNames = this.getTableNames(normalized);
    let completed = 0;

    progressCallback({
      step: `Dropping ${tableNames.length} tables in parallel (${tableNames.length} sessions)...`,
      progress: 0
    });

    await Promise.all(tableNames.map(async (tableName) => {
      const connection = await oracleDb.createDirectConnection();

      try {
        await connection.execute(`DROP TABLE ${tableName} PURGE`);
      } catch (error) {
        if (error.errorNum !== 942) {
          throw error;
        }
      } finally {
        await connection.close();
      }

      completed += 1;
      progressCallback({
        step: `Dropped ${completed}/${tableNames.length} tables...`,
        progress: Math.round((completed / tableNames.length) * 100)
      });
    }));

    progressCallback({
      step: `Dropped insert-blast tables for prefix ${normalized.tablePrefix}.`,
      progress: 100
    });

    return {
      config: normalized,
      tableNames
    };
  }

  async getStatus(oracleDb, config = {}) {
    const normalized = this.normalizeConfig(config);
    const tableNames = this.getTableNames(normalized);
    const escapedPrefix = normalized.tablePrefix
      .replace(/\\/g, '\\\\')
      .replace(/_/g, '\\_')
      .replace(/%/g, '\\%');
    const likePattern = `${escapedPrefix}\\_T%`;

    const result = await oracleDb.execute(
      `
        SELECT table_name, num_rows
        FROM user_tables
        WHERE table_name LIKE :likePattern ESCAPE '\\'
        ORDER BY table_name
      `,
      { likePattern }
    );

    const expectedSet = new Set(tableNames);
    const prefixMatches = (result.rows || []).map((row) => ({
      tableName: row.TABLE_NAME,
      estimatedRows: Number(row.NUM_ROWS || 0)
    }));
    const existing = prefixMatches
      .map((row) => ({
        tableName: row.tableName,
        estimatedRows: row.estimatedRows
      }))
      .filter((row) => expectedSet.has(row.tableName));

    return {
      config: normalized,
      ready: existing.length === tableNames.length,
      existingTables: existing,
      existingTableCount: prefixMatches.length,
      prefixMatchedTables: prefixMatches,
      missingTables: tableNames.filter((name) => !existing.some((row) => row.tableName === name))
    };
  }

  async getUserSessionsByInstance(oracleDb) {
    const connectedUser = String(oracleDb.getStatus()?.config?.user || '').trim().toUpperCase();

    if (!connectedUser) {
      return {
        username: '',
        source: null,
        sessions: [],
        error: null
      };
    }

    const buildRows = (rows = [], source, error = null) => ({
      username: connectedUser,
      source,
      error,
      sessions: rows.map((row) => ({
        instId: Number(row.INST_ID || 1),
        totalSessions: Number(row.TOTAL_SESSIONS || 0),
        activeSessions: Number(row.ACTIVE_SESSIONS || 0),
        inactiveSessions: Number(row.INACTIVE_SESSIONS || 0)
      }))
    });

    try {
      const result = await oracleDb.execute(
        `
          SELECT
            inst_id,
            COUNT(*) AS total_sessions,
            SUM(CASE WHEN status = 'ACTIVE' THEN 1 ELSE 0 END) AS active_sessions,
            SUM(CASE WHEN status = 'INACTIVE' THEN 1 ELSE 0 END) AS inactive_sessions
          FROM gv$session
          WHERE type = 'USER'
            AND username = :connectedUser
          GROUP BY inst_id
          ORDER BY inst_id
        `,
        { connectedUser }
      );

      return buildRows(result.rows, 'gv$session');
    } catch (error) {
      try {
        const fallback = await oracleDb.execute(
          `
            SELECT
              1 AS inst_id,
              COUNT(*) AS total_sessions,
              SUM(CASE WHEN status = 'ACTIVE' THEN 1 ELSE 0 END) AS active_sessions,
              SUM(CASE WHEN status = 'INACTIVE' THEN 1 ELSE 0 END) AS inactive_sessions
            FROM v$session
            WHERE type = 'USER'
              AND username = :connectedUser
          `,
          { connectedUser }
        );

        return buildRows(fallback.rows, 'v$session');
      } catch (fallbackError) {
        return buildRows([], null, fallbackError.message);
      }
    }
  }

  async getLmsProcessMemory(oracleDb) {
    const buildRows = (rows = [], source, error = null) => ({
      source,
      error,
      rows: rows.map((row) => ({
        instId: Number(row.INST_ID || 1),
        pid: Number(row.PID || 0),
        osPid: row.OS_PID,
        processName: row.PROCESS_NAME,
        pgaUsedMb: Number(row.PGA_USED_MB || 0),
        pgaAllocMb: Number(row.PGA_ALLOC_MB || 0),
        category: row.CATEGORY,
        allocMb: Number(row.ALLOC_MB || 0),
        usedMb: Number(row.USED_MB || 0)
      }))
    });

    try {
      const result = await oracleDb.execute(`
        SELECT
          p.inst_id,
          p.pid,
          p.spid AS os_pid,
          p.pname AS process_name,
          ROUND(p.pga_used_mem / 1024 / 1024, 2) AS pga_used_mb,
          ROUND(p.pga_alloc_mem / 1024 / 1024, 2) AS pga_alloc_mb,
          m.category,
          ROUND(m.allocated / 1024 / 1024, 3) AS alloc_mb,
          ROUND(m.used / 1024 / 1024, 3) AS used_mb
        FROM gv$process p
        JOIN gv$process_memory m
          ON m.inst_id = p.inst_id
         AND m.pid = p.pid
        WHERE p.pname LIKE 'LMS%'
        ORDER BY p.pga_used_mem DESC, m.allocated DESC
        FETCH FIRST 40 ROWS ONLY
      `);

      return buildRows(result.rows, 'gv$process/gv$process_memory');
    } catch (error) {
      try {
        const fallback = await oracleDb.execute(`
          SELECT
            1 AS inst_id,
            p.pid,
            p.spid AS os_pid,
            p.pname AS process_name,
            ROUND(p.pga_used_mem / 1024 / 1024, 2) AS pga_used_mb,
            ROUND(p.pga_alloc_mem / 1024 / 1024, 2) AS pga_alloc_mb,
            m.category,
            ROUND(m.allocated / 1024 / 1024, 3) AS alloc_mb,
            ROUND(m.used / 1024 / 1024, 3) AS used_mb
          FROM v$process p
          JOIN v$process_memory m
            ON m.pid = p.pid
          WHERE p.pname LIKE 'LMS%'
          ORDER BY p.pga_used_mem DESC, m.allocated DESC
          FETCH FIRST 40 ROWS ONLY
        `);

        return buildRows(fallback.rows, 'v$process/v$process_memory');
      } catch (fallbackError) {
        return buildRows([], null, fallbackError.message);
      }
    }
  }

  async getMonitorSnapshot(oracleDb) {
    const [userSessions, lmsProcessMemory] = await Promise.all([
      this.getUserSessionsByInstance(oracleDb),
      this.getLmsProcessMemory(oracleDb)
    ]);

    const warnings = [
      userSessions?.error ? `User sessions: ${userSessions.error}` : null,
      lmsProcessMemory?.error ? `LMS process memory: ${lmsProcessMemory.error}` : null
    ].filter(Boolean);

    return {
      timestamp: Date.now(),
      userSessions,
      lmsProcessMemory,
      warnings
    };
  }
}

module.exports = new InsertBlastManager();
