class InsertBlastManager {
  normalizeConfig(config = {}) {
    const tablePrefix = String(config.tablePrefix || 'IBLAST').trim().toUpperCase().replace(/[^A-Z0-9_$#]/g, '');
    const tableCount = Math.max(1, Math.min(5000, Number.parseInt(config.tableCount, 10) || 8));
    const columnsPerTable = Math.max(4, Math.min(200, Number.parseInt(config.columnsPerTable, 10) || 24));

    if (!tablePrefix) {
      throw new Error('Table prefix is required.');
    }

    return {
      tablePrefix,
      tableCount,
      columnsPerTable
    };
  }

  getTableNames(config = {}) {
    const normalized = this.normalizeConfig(config);
    return Array.from({ length: normalized.tableCount }, (_, index) => (
      `${normalized.tablePrefix}_T${String(index + 1).padStart(3, '0')}`
    ));
  }

  buildColumnDefinitions(columnsPerTable) {
    const columns = [
      'id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
      'created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL'
    ];

    for (let index = 1; index <= columnsPerTable; index += 1) {
      const suffix = String(index).padStart(3, '0');
      if (index % 3 === 1) {
        columns.push(`vc_${suffix} VARCHAR2(100)`);
      } else if (index % 3 === 2) {
        columns.push(`num_${suffix} NUMBER(18,2)`);
      } else {
        columns.push(`dt_${suffix} DATE`);
      }
    }

    return columns;
  }

  generateCreateTableDDL(tableName, columnsPerTable) {
    const columns = this.buildColumnDefinitions(columnsPerTable);
    return `CREATE TABLE ${tableName} (\n  ${columns.join(',\n  ')}\n) NOLOGGING`;
  }

  async createTables(oracleDb, config = {}, progressCallback = () => {}) {
    const normalized = this.normalizeConfig(config);
    const tableNames = this.getTableNames(normalized);
    const connection = await oracleDb.getConnection();

    try {
      for (let index = 0; index < tableNames.length; index += 1) {
        const tableName = tableNames[index];
        progressCallback({
          step: `Creating ${tableName}...`,
          progress: Math.round((index / tableNames.length) * 100)
        });
        await connection.execute(this.generateCreateTableDDL(tableName, normalized.columnsPerTable), [], {
          autoCommit: false
        });
      }

      await connection.commit();
      progressCallback({
        step: `Created ${tableNames.length} insert-blast table(s).`,
        progress: 100
      });

      return {
        config: normalized,
        tableNames
      };
    } finally {
      await connection.close();
    }
  }

  async dropTables(oracleDb, config = {}, progressCallback = () => {}) {
    const normalized = this.normalizeConfig(config);
    const tableNames = this.getTableNames(normalized);
    let completed = 0;

    progressCallback({
      step: `Dropping ${tableNames.length} tables in parallel (${tableNames.length} sessions)...`,
      progress: 0
    });

    await Promise.all(tableNames.map(async (tableName) => {
      const connection = await oracleDb.createDirectConnection();

      try {
        await connection.execute(`DROP TABLE ${tableName} PURGE`);
      } catch (error) {
        if (error.errorNum !== 942) {
          throw error;
        }
      } finally {
        await connection.close();
      }

      completed += 1;
      progressCallback({
        step: `Dropped ${completed}/${tableNames.length} tables...`,
        progress: Math.round((completed / tableNames.length) * 100)
      });
    }));

    progressCallback({
      step: `Dropped insert-blast tables for prefix ${normalized.tablePrefix}.`,
      progress: 100
    });

    return {
      config: normalized,
      tableNames
    };
  }

  async getStatus(oracleDb, config = {}) {
    const normalized = this.normalizeConfig(config);
    const tableNames = this.getTableNames(normalized);
    const escapedPrefix = normalized.tablePrefix
      .replace(/\\/g, '\\\\')
      .replace(/_/g, '\\_')
      .replace(/%/g, '\\%');
    const likePattern = `${escapedPrefix}\\_T%`;

    const result = await oracleDb.execute(
      `
        SELECT table_name, num_rows
        FROM user_tables
        WHERE table_name LIKE :likePattern ESCAPE '\\'
        ORDER BY table_name
      `,
      { likePattern }
    );

    const expectedSet = new Set(tableNames);
    const existing = (result.rows || [])
      .map((row) => ({
        tableName: row.TABLE_NAME,
        estimatedRows: Number(row.NUM_ROWS || 0)
      }))
      .filter((row) => expectedSet.has(row.tableName));

    return {
      config: normalized,
      ready: existing.length === tableNames.length,
      existingTables: existing,
      missingTables: tableNames.filter((name) => !existing.some((row) => row.tableName === name))
    };
  }
}

module.exports = new InsertBlastManager();
